language: node_js
node_js:
- 11
script:
- make test
deploy:
  provider: npm
  email: npm@gatti.email
  api_key:
    secure: gmuudWRNHcJPvLyqj+K0J0PKWIzxprJNRzWXEPmfO+sv6dTYTjnZfRRXd4XR9JO9IrvyeS9T3KD6vdiGlYg/CZyRNF1w9isuaxd0V33CPIzUcfnNSx5NCGeJYzxJGXJk355pttAqHEiTH3Yl+NjqhJo/+/aYBKjYaVua4/Ec2fscQ/k4JnBY9fKX+MA/2sXQ/9BHqZc/LyyqPloMb5H9NhtFRsTYSuu35oKzW0bVCegJjqBZQ+/xhpg+SgU1jlpcxIxPoqW4cAnX5JgfQU7hT2RHF1/d243H4JYJ7A6gvW/kWkBJ2KPWCDt0Lv3u4JgZON3I48D6eSRaQoNfmKcbZw+flU7NZfDo+gQY4FwyssKREwbPoOEVNXIyfk8RJ+eVWWv0Z508snfeBAHrg0WqAsqNeYxquDHJ6fDba49ovHOnrZMvzscCj05XCTp4NYC0XvUMJL0lEoF03dSAj+4rmN4nGpiOINnMzyzs5LoMdeBoqK0l4qsIqG9tfHfEvi9658IiT2xocWh3VdhKZYPgdb+g7/cxnj32D2phqn8ut4yilW8V5wcIPACPYv4BNq3eB60mxF/cbSLHxcwoabHhlebxT29cd1R5m+NXz/Kl53Q48L9q4dH5Lt36IUrVKdPHY5qgUP0mPbe4hW0TO3RT/wAZTpHuSptxf+iBnCHLbdM=
  on:
    tags: false
    branch: master
    repo: 0x4447/0x4447-cli-node-tomato
    node_js: '8'
